MSVC: Fix build failures with VS2010
This compiler does not like 'using' keyword after operator has been defined:
 ...\lib\src\Base\Type\SquareMatrix.hxx(148) : error C2668: 'OT::Matrix::operator *' : ambiguous call to overloaded function
    ...\lib\src\base\type\Matrix.hxx(141): could be 'OT::Matrix OT::Matrix::operator *(const OT::NumericalScalar) const'
    ...\lib\src\Base\Type\SquareMatrix.hxx(107): or 'OT::SquareMatrix OT::SquareMatrix::operator *(const OT::NumericalScalar) const'
    while trying to match the argument list '(const OT::NumericalScalar)'