Fix Mingw autobuilder
Mingw build currently fails on this branch, with this message:
  err:module:import_dll Loading library libOT.dll (which is needed by L"Z:\\home\\openturns\\distcheck\\last\\sid-x86_64-ot-mingw\\Lib\\site-packages\\openturns\\_common.pyd") failed (error c0000017).
  Traceback (most recent call last):
    File "/home/openturns/distcheck/workdir/python/test/t_ComparisonOperator_std.py", line 3, in <module>
      from openturns import *
    File "Z:\home\openturns\distcheck\last\sid-x86_64-ot-mingw\Lib\site-packages\openturns\__init__.py", line 95, in <module>
      from .common import *
    File "Z:\home\openturns\distcheck\last\sid-x86_64-ot-mingw\Lib\site-packages\openturns\common.py", line 32, in <module>
      _common = swig_import_helper()
    File "Z:\home\openturns\distcheck\last\sid-x86_64-ot-mingw\Lib\site-packages\openturns\common.py", line 28, in swig_import_helper
      _mod = imp.load_module('_common', fp, pathname, description)
  ImportError: DLL load failed: Module not found.

This is weird, since libOT.dll is copied into python/test.
Moreover tests do run fine interactively or from a shell script, but not when
called via a Makefile.  A workaround is to use stripped libraries, no idea why
this works.

distcheck ok.